### ISSUE TITLE
css居中总结

### ISSUE THREAD

**Issue by FridaS** [FridaS/blog#21]
## css居中总结
2019年01月16日

DOM结构：

```html
<div class="parent">
    <div class="child">DEMO</div>
</div>
```

注：下文的“容器”在不特殊说明情况下都是指目标容器，即我们想让其居中的目标元素（class为child的div）。

#### 垂直居中

一、单行文本

设置line-height等于height。

- 优点：同时支持块级元素和内联元素；支持所有的浏览器；
- 缺点：只适合单行。

二、容器高度固定

1. Negative margins（负外边距）

   ```css
   .parent{
       height: 100%;
       position: relative;
   }
   .child{
       height: 50px; // 容器高度固定
       position: absolute;
       top: 50%;
       margin-top: -25px;
   }
   ```

   - 优点：兼容性好（测试IE7可兼容）；
   - 缺点：定高；计算margin-top要考虑其他值，如padding、border；溢出问题。

2. Absolute Centering（绝对居中）

   ```css
   .parent{
       height: 100%;
       position: relative;
   }
   .child{
       height: 50px;
       position: absolute;
       top: 0;
       bottom: 0;
       margin: auto 0;
   }
   ```

   - 优点：兼容性好；高度可以为%形式；
   - 缺点：定高。

3. 插入额外元素

   ```html
   <div class="parent">
       <!-- 在child前插入brother -->
       <div class="brother"></div>
       <div class="child">DEMO</div>
   </div>
   ```

   ```css
   .parent{
       height: 100%;
   }
   .brother{
       height: 50%;
       margin-bottom: -25px;
   }
   .child{
       height: 50px;
   }
   ```

   - 优点：兼容性好；
   - 缺点：需要额外的空元素。

三、容器高度不定

1. table-cell + vertical-align

   ```css
   .parent{
       height: 100px;
       display: table-cell;
       vertical-align: middle;
   }
   ```

   - 优点：兼容性好（可以兼容到IE8，若要兼容IE6、7，将元素等换成table、td等元素即可）

2. absolute + transform

   ```css
   .parent{
       height: 100%;
       position: relative;
   }
   .child{
       position: absolute;
       top: 50%;
       -webkit-transform: translateY(-50%);
       -moz-transform: translateY(-50%);
       -ms-transform: translateY(-50%);
       -o-transform: translateY(-50%);
       transform: translateY(-50%);
   }
   ```

   - 优点：根据自身高度偏移，所以不需要指定容器高度；

   - 缺点：要适配各种浏览器；IE8及以下不支持。

     ​

3. flex + align-items

   ```css
   .parent{
       height: 100%;
       display: flex;
       align-items: center;
   }
   ```

   - 优点：内容块宽高任意；可用于更复杂高级的布局，代码简洁易读（Flexbox设计初衷就是为了解决像垂直居中这种常见的布局问题）。
   - 缺点：兼容问题。

   以上样式的兼容版：

   ```css
   .parent{
       height: 100%;
       display: -webkit-box; /* OLD - ios 6-, Safari 3.1-6 */
       display: -moz-box; /* OLD - Firefox 19- (buggy but mostly works) */
       display: -ms-flexbox; /* TWEENER - IE 10 */
       display: -webkit-flex; /* NEW - Chrome */
       display: flex; /* NEW - Spec - Opera 12.1, Firefox 20+ */
       -webkit-box-align: center; /* 09版 */
       -webkit-box-pack: center; /* 12版 */
       -moz-box-pack: center;
       -ms-flex-align: center; /* IE 10 */
       -webkit-align-items: center;
       -moz-align-items: center;
       align-items: center;
   }
   ```

   ​

4. inline-block + vertical-align + 伪元素

   ```css
   .parent:before{
       content: '';
       display: inline-block;
       height: 100%;
       vertical-align: middle;
       margin-left: -0.5em;
   }
   .child{
       display: inline-block;
       vertical-align: middle;
       max-width: 100%;
   }
   ```

   - 优点：兼容性好，兼容IE8+（IE7不支持伪元素）；
   - 缺点：这种方法其实和table-cell方法差不多，但是显然代码比table-cell的多。

   注：

   - font-size设置的是字体的高度，宽度要根据具体字符而定,英文字符0.5em，中文字符是宽高一致的、所以是1em。content:’’;会占0.5em；

   - 如果不用margin-left:-0.5em;也可以：

     ```css
     .parent{
         font-size: 0;
     }
     .child{
         font-size: 16px;
     }
     ```

   - 这里.child必须设置max-width:100%;因为如果child超过parent宽度，child会被挤到底部。

#### 水平居中

一、容器宽度固定

1. block + margin:0 auto

   ```css
   .child{ /* .child是block元素 */
       width: 100px;
       margin: 0 auto;
   }
   ```

   - 优点：简单易懂，浏览器兼容性强；
   - 缺点：定宽（width:50%;百分比表示法这里也认为定宽）。

二、容器宽度不定的情况

1. inline-block + text-align

   ```css
   .parent{
       text-align: center;
   }
   .child{
       display: inline-block;
   }
   ```

   注：inline-block元素宽度根据内容决定，block元素宽度撑满父元素。

   - 优点：兼容性好，到IE6、7；
   - 缺点：child中的文字也继承了水平居中，如果不想居中，需要额外写样式。

2. table + margin

   ```css
   .child{
       display: table;
       margin: 0 auto;
   }
   ```

   - 优点：不需要在父元素上设置样式。

   注：

   - table表现上很像block、所以可以用margin居中，但是其宽度是根据内容而定的；
   - 如果单纯的display:block;直接用margin:0 auto;是不能居中的，必须指定width。

3.  absolute + transform

   ```css
   .parent{
       position: relative;
   }
   .child{
       position: absolute;
       left: 50%;
       -webkit-transform: translateX(-50%);
       -moz-transform: translateX(-50%);
       -ms-transform: translateX(-50%);
       -o-transform: translateX(-50%);
       transform: translateX(-50%);
   }
   ```

   注：absolute后元素宽度由内容决定。

   - 优点：绝对定位脱离文档流、不会对其他元素产生影响；
   - 缺点：CSS3兼容性问题。

4. margin + transform

   ```css
   .child{
       margin-left: 50%;
       transform: translateX(-50%);
   }
   ```

   - 缺点：兼容性问题。

5. flex + justify-content
   父元素是flex，子元素自然是flex-item，flex-item默认情况下宽度为内容宽度。
   1）方案一

   ```css
   .parent{
       display: flex;
       justify-content: center;
   }
   ```

   - 优点：只需要设置parent的样式；
   - 缺点：兼容性。

   2）方案二

   ```css
   .parent{
       display: flex;
   }
   .child{
       margin: 0 auto;
   }
   ```

   - 缺点：兼容性。

#### 水平、垂直居中

综上，在容器宽高未知时，设置水平、垂直居中的方案有：

1. inline-block + text-align + table-cell + vertical-align
2. absolute + transform
3. flex + justify-content + align-items

当然还有其他方法（有空再学习总结下）：

1. https://www.zhangxinxu.com/wordpress/2016/05/css3-width-max-contnet-min-content-fit-content/
2. https://www.zhangxinxu.com/wordpress/2016/04/css-writing-mode/
