### ISSUE TITLE
CSS效果实现积累

### ISSUE THREAD

**Issue by FridaS** [FridaS/blog#6]
主要是记录工作学习过程中遇到的CSS问题，以供以后回顾查看。

1. 需求：input输入框placeholder文字颜色和输入的文字颜色不同
解决：
    - 输入文字颜色用color即可
    - placeholder文字颜色可以用2种方式修改——伪元素、伪类：
        - Webkit、Blink（Safari、Google Chrome、Opera 15+）、Microsoft Edge通过伪元素 ::-webkit-input-placeholder
        - Mozilla Firefox 4 到 8使用伪类 :-moz-placeholder
        - Mozilla Firefox 19+使用伪元素 ::-moz-placeholder
        - Internet Explorer 10 和 11使用伪类 :-ms-input-placeholder
        - 大多数现代浏览器可以使用没有前缀的伪元素 ::placeholder
        - IE 9及以下浏览器不支持 placeholder 属性，Opera 12及以下浏览器不支持任何placeholder的CSS选择器

    参考：https://stackoverflow.com/questions/2610497/change-an-html5-inputs-placeholder-color-with-css
2. 需求：文本溢出显示省略号(...)
解决：
    - 单行文本：
        ```
        max-width:100px; //需要设置宽度或者最大宽度
        overflow:hidden;
        text-overflow:ellipsis;
        white-space: nowrap;
        ```
    - 多行文本：
        ```
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 3; // 显示行数
        overflow: hidden;
        text-overflow:ellipsis;
        ```

    参考：http://www.daqianduan.com/6179.html
3. border-style设为dashed或dotted时的虚线间距无法改变，用背景图片来模拟
```
    background-image: linear-gradient(to right, #ddd 0%, #ddd 50%, transparent 50%);
    background-size: 11px 1px;
    background-repeat: repeat-x;
```
对比用border-style：
```
border-bottom: 1px dashed #ddd;
```
![](http://thyrsi.com/t6/376/1538033803x-1404729656.jpg)

4. 用CSS实现三角形。
    - 使用border属性，这是一种简写形式，它可以按顺序设置以下3个属性：
        - border-width：对顶边框的宽度；
        - border-style：规定边框的样式；
        - border-color：规定边框的颜色。
    ```css
    .triangle {
        width: 0;
        height: 0;
        border-width: 50px;
        border-style: solid;
        border-color: blue transparent transparent transparent;
    }
    ```
    ![](https://haitao.nos.netease.com/c4655f44-47df-4bcb-af57-2d7d678407f5_230_224.jpg)

    我们可以通过border-width来设置4面边框的长度、从而改变三角形各边长；通过border-style来设置不同图形（比如扇形）；通过border-color来设置三角形朝向（上下左右4面三角形）。

    ```css
    .triangle {
        width: 0;
        height: 0;
        border-width: 50px 20px 60px 70px;
        border-style: solid;
        border-color: transparent transparent red transparent;
    }
    ```
    ![](https://haitao.nos.netease.com/f6db2a17-49d1-4beb-a7d4-ab3780ab78d2_304_338.jpg)
    
    从下图可以看到border-width设置情况：
    ![](https://haitao.nos.netease.com/d4b3b52e-3da0-41d7-a7a8-82fdec001400_426_360.jpg)
    
    参考：
    - [CSS border属性](http://www.w3school.com.cn/cssref/pr_border.asp)
    - [用CSS画基本图形](https://www.cnblogs.com/jscode/archive/2012/10/19/2730905.html)
